# Generated by Django 5.2.3 on 2025-06-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_address', models.CharField(max_length=200)),
                ('zoning', models.CharField(blank=True, max_length=20)),
                ('units', models.IntegerField(default=1)),
                ('use_description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Cold', 'Cold'), ('Warm', 'Warm'), ('Qualified', 'Qualified')], default='Cold', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_zip', models.CharField(blank=True, max_length=20)),
                ('building_value', models.IntegerField(blank=True, null=True)),
                ('land_value', models.IntegerField(blank=True, null=True)),
                ('total_value', models.IntegerField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('lot_size', models.FloatField(blank=True, null=True)),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('sale_date', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
