# Generated by Django 5.2.3 on 2025-06-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_lead_owner_email_remove_lead_owner_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='owner_name_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
