# Generated by Django 5.2.3 on 2025-06-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_owner_name_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='mailing_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
