# Generated by Django 5.2.3 on 2025-10-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_savedparcellist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkipTraceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_id', models.IntegerField(blank=True, null=True)),
                ('loc_id', models.CharField(max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['town_id', 'loc_id'], name='leads_skipt_town_id_77b4f8_idx')],
                'unique_together': {('town_id', 'loc_id')},
            },
        ),
    ]
