# Generated by Django 5.2.3 on 2025-10-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_schedulecallrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='schedulecallrequest',
            new_name='leads_sched_town_id_7037a5_idx',
            old_name='leads_sched_town_id_d49fdb_idx',
        ),
    ]
