# Generated by Django 5.2.3 on 2025-10-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_generatedmailer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='generatedmailer',
            new_name='leads_gener_town_id_0a356d_idx',
            old_name='leads_gener_town_id_0b9642_idx',
        ),
    ]
