# Generated by Django 5.2.3 on 2025-10-30 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_remove_lead_notes_lead_saved_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attomdata',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='saved_list',
        ),
        migrations.AddField(
            model_name='attomdata',
            name='loc_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='saved_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attom_data', to='leads.savedparcellist'),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='town_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
