# Generated by Django 5.2.3 on 2025-10-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_attomdata_foreclosure_auction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attomdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='attomdata',
            index=models.Index(fields=['town_id', 'loc_id'], name='leads_attom_town_id_e348f5_idx'),
        ),
        migrations.AddIndex(
            model_name='attomdata',
            index=models.Index(fields=['last_updated'], name='leads_attom_last_up_3e1f34_idx'),
        ),
    ]
