# Generated by Django 5.2.3 on 2025-10-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_mailing_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedParcelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('town_id', models.IntegerField()),
                ('town_name', models.CharField(max_length=100)),
                ('criteria', models.JSONField()),
                ('loc_ids', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
