# Generated by Django 5.2.3 on 2025-10-27 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_schedulecallrequest_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='skiptracerecord',
            name='leads_skipt_town_id_77b4f8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='skiptracerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='skiptracerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skiptrace_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='skiptracerecord',
            unique_together={('created_by', 'town_id', 'loc_id')},
        ),
        migrations.AddIndex(
            model_name='skiptracerecord',
            index=models.Index(fields=['created_by', 'town_id', 'loc_id'], name='leads_skipt_created_0b4994_idx'),
        ),
    ]
