# Generated by Django 5.2.3 on 2025-10-30 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_remove_skiptracerecord_leads_skipt_town_id_77b4f8_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_foreclosure', models.BooleanField(default=False)),
                ('mortgage_default', models.BooleanField(default=False)),
                ('tax_default', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attom_data', to='leads.lead')),
            ],
        ),
    ]
