# Generated by Django 5.2.3 on 2025-10-30 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_attomdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='notes',
        ),
        migrations.AddField(
            model_name='lead',
            name='saved_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.savedparcellist'),
        ),
    ]
