# Generated by Django 5.1.6 on 2025-11-03 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_legalaction_lienrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LienSearchAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_id', models.IntegerField(db_index=True)),
                ('loc_id', models.CharField(db_index=True, max_length=200)),
                ('searched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('found_liens', models.BooleanField(default=False)),
                ('found_legal_actions', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lien_search_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leads_lien_search_attempt',
                'indexes': [models.Index(fields=['created_by', 'town_id', 'loc_id'], name='leads_lien__created_d1d5a4_idx'), models.Index(fields=['searched_at'], name='leads_lien__searche_2d38ce_idx')],
                'unique_together': {('created_by', 'town_id', 'loc_id')},
            },
        ),
    ]
