# Generated by Django 5.2.3 on 2025-11-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_mailertemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassGISParcelCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_id', models.IntegerField(db_index=True)),
                ('loc_id', models.CharField(db_index=True, max_length=200)),
                ('parcel_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'MassGIS Parcel Cache',
                'verbose_name_plural': 'MassGIS Parcel Cache',
                'indexes': [models.Index(fields=['town_id', 'loc_id'], name='leads_massg_town_id_34a603_idx'), models.Index(fields=['last_accessed'], name='leads_massg_last_ac_8089c0_idx')],
                'unique_together': {('town_id', 'loc_id')},
            },
        ),
    ]
