# Generated by Django 5.2.3 on 2025-11-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_schedulecallrequest_crm_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(db_index=True, help_text='State-issued entity ID number', max_length=50, unique=True)),
                ('entity_name', models.CharField(db_index=True, help_text='Legal name of the entity', max_length=255)),
                ('entity_type', models.CharField(choices=[('llc', 'Limited Liability Company'), ('corp', 'Corporation'), ('lp', 'Limited Partnership'), ('gp', 'General Partnership'), ('trust', 'Business Trust'), ('other', 'Other')], default='llc', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('dissolved', 'Dissolved'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('merged', 'Merged'), ('unknown', 'Unknown')], db_index=True, default='active', max_length=20)),
                ('principal_name', models.CharField(blank=True, help_text='Name of managing member, president, or principal officer', max_length=255, null=True)),
                ('principal_title', models.CharField(blank=True, help_text='Title (e.g., Managing Member, President, Manager)', max_length=100, null=True)),
                ('registered_agent', models.CharField(blank=True, help_text='Name of registered agent for legal service', max_length=255, null=True)),
                ('business_phone', models.CharField(blank=True, help_text='Primary business phone number', max_length=20, null=True)),
                ('business_email', models.EmailField(blank=True, help_text='Primary business email', max_length=254, null=True)),
                ('business_address', models.TextField(blank=True, help_text='Principal office address', null=True)),
                ('formation_date', models.DateField(blank=True, help_text='Date entity was formed/incorporated', null=True)),
                ('last_annual_report', models.DateField(blank=True, help_text='Date of most recent annual report filing', null=True)),
                ('source_url', models.URLField(blank=True, help_text='URL of the source record', null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Raw scraped data for audit trail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='Used for 180-day cache freshness checks')),
            ],
            options={
                'verbose_name': 'Corporate Entity',
                'verbose_name_plural': 'Corporate Entities',
                'db_table': 'leads_corporate_entity',
                'ordering': ['-last_updated', 'entity_name'],
            },
        ),
        migrations.RenameIndex(
            model_name='schedulecallrequest',
            new_name='leads_sched_stage_2d1b5f_idx',
            old_name='leads_sched_stage_is_ar_idx',
        ),
        migrations.AddIndex(
            model_name='corporateentity',
            index=models.Index(fields=['entity_name'], name='leads_corpo_entity__58ba2d_idx'),
        ),
        migrations.AddIndex(
            model_name='corporateentity',
            index=models.Index(fields=['entity_id'], name='leads_corpo_entity__fc3cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='corporateentity',
            index=models.Index(fields=['status'], name='leads_corpo_status_b9bd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='corporateentity',
            index=models.Index(fields=['last_updated'], name='leads_corpo_last_up_385c27_idx'),
        ),
        migrations.AddIndex(
            model_name='corporateentity',
            index=models.Index(fields=['principal_name'], name='leads_corpo_princip_b81cf4_idx'),
        ),
    ]
