# Generated by Codex on demand

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_corporateentity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelMarketValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_id', models.IntegerField(db_index=True)),
                ('loc_id', models.CharField(max_length=200)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, help_text='Final blended market value (USD).', max_digits=16, null=True)),
                ('market_value_per_sqft', models.DecimalField(blank=True, decimal_places=2, help_text='Blended price per interior square foot.', max_digits=12, null=True)),
                ('comparable_value', models.DecimalField(blank=True, decimal_places=2, help_text='Weighted comparable sale estimate used in blend.', max_digits=16, null=True)),
                ('comparable_count', models.IntegerField(default=0)),
                ('comparable_avg_psf', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hedonic_value', models.DecimalField(blank=True, decimal_places=2, help_text='Regression output before blending.', max_digits=16, null=True)),
                ('hedonic_r2', models.FloatField(blank=True, null=True)),
                ('valuation_confidence', models.FloatField(blank=True, help_text='0-1 score derived from data coverage.', null=True)),
                ('methodology', models.CharField(choices=[('hybrid_v1', 'Hybrid Hedonic + Comps v1')], default='hybrid_v1', max_length=50)),
                ('model_version', models.CharField(default='hybrid-v1.0', max_length=50)),
                ('valued_at', models.DateTimeField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-valued_at', 'town_id', 'loc_id'],
                'unique_together': {('town_id', 'loc_id')},
            },
        ),
        migrations.AddIndex(
            model_name='parcelmarketvalue',
            index=models.Index(fields=['town_id', 'loc_id'], name='leads_parcel_town_loc_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelmarketvalue',
            index=models.Index(fields=['valued_at'], name='leads_parcel_valued_idx'),
        ),
    ]
