# Generated by Django 5.2.3 on 2025-11-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_parcelmarketvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassGISParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_id', models.IntegerField(db_index=True)),
                ('loc_id', models.CharField(max_length=200)),
                ('site_address', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('site_city', models.CharField(blank=True, max_length=100, null=True)),
                ('site_zip', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('owner_name', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('owner_address', models.TextField(blank=True, null=True)),
                ('owner_city', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_state', models.CharField(blank=True, max_length=2, null=True)),
                ('owner_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('absentee', models.BooleanField(db_index=True, default=False)),
                ('use_code', models.CharField(blank=True, max_length=20, null=True)),
                ('property_type', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('property_category', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('style', models.CharField(blank=True, max_length=100, null=True)),
                ('zoning', models.CharField(blank=True, max_length=50, null=True)),
                ('total_value', models.IntegerField(blank=True, db_index=True, null=True)),
                ('land_value', models.IntegerField(blank=True, null=True)),
                ('building_value', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.FloatField(blank=True, null=True)),
                ('lot_units', models.CharField(blank=True, max_length=20, null=True)),
                ('living_area', models.IntegerField(blank=True, null=True)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.FloatField(blank=True, null=True)),
                ('year_built', models.IntegerField(blank=True, db_index=True, null=True)),
                ('last_sale_date', models.DateField(blank=True, db_index=True, null=True)),
                ('last_sale_price', models.IntegerField(blank=True, null=True)),
                ('equity_percent', models.FloatField(blank=True, db_index=True, null=True)),
                ('years_owned', models.FloatField(blank=True, db_index=True, null=True)),
                ('centroid_lon', models.FloatField(blank=True, db_index=True, null=True)),
                ('centroid_lat', models.FloatField(blank=True, db_index=True, null=True)),
                ('geometry', models.JSONField(blank=True, help_text='GeoJSON polygon for parcel boundary', null=True)),
                ('fiscal_year', models.CharField(blank=True, max_length=10, null=True)),
                ('data_source', models.CharField(blank=True, default='massgis', max_length=50, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['town_id', 'loc_id'],
            },
        ),
        migrations.RenameIndex(
            model_name='parcelmarketvalue',
            new_name='leads_parce_town_id_51d356_idx',
            old_name='leads_parcel_town_loc_idx',
        ),
        migrations.RenameIndex(
            model_name='parcelmarketvalue',
            new_name='leads_parce_valued__e36ef3_idx',
            old_name='leads_parcel_valued_idx',
        ),
        migrations.AddIndex(
            model_name='massgisparcel',
            index=models.Index(fields=['town_id', 'loc_id'], name='leads_massg_town_id_149e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='massgisparcel',
            index=models.Index(fields=['property_category', 'total_value'], name='leads_massg_propert_ed12a2_idx'),
        ),
        migrations.AddIndex(
            model_name='massgisparcel',
            index=models.Index(fields=['absentee', 'total_value'], name='leads_massg_absente_628dad_idx'),
        ),
        migrations.AddIndex(
            model_name='massgisparcel',
            index=models.Index(fields=['centroid_lon', 'centroid_lat'], name='leads_massg_centroi_82edc4_idx'),
        ),
        migrations.AddIndex(
            model_name='massgisparcel',
            index=models.Index(fields=['last_sale_date'], name='leads_massg_last_sa_3bf1b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='massgisparcel',
            unique_together={('town_id', 'loc_id')},
        ),
    ]
