# Generated by Django 5.2.3 on 2025-11-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_massgisparcel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massgisparcel',
            name='building_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='massgisparcel',
            name='land_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='massgisparcel',
            name='last_sale_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='massgisparcel',
            name='total_value',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
