# Generated by Django 5.2.3 on 2025-10-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='billing_status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_amount_cents',
            field=models.PositiveIntegerField(default=2500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_id',
            field=models.CharField(default='individual_standard', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
