"""
Django settings for leadcrm project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from decimal import ROUND_HALF_UP, Decimal, InvalidOperation
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a local .env file if present
_env_candidates = [
    BASE_DIR / ".env",          # inner project directory
    BASE_DIR.parent / ".env",   # repo root (one level up)
]
for ENV_PATH in _env_candidates:
    if not ENV_PATH.exists():
        continue
    for raw_line in ENV_PATH.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip())
    break


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("DJANGO_SECRET_KEY environment variable is required")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")

# Railway-provided metadata
RAILWAY_STATIC_URL = os.getenv("RAILWAY_STATIC_URL", "").strip()
RAILWAY_PUBLIC_DOMAIN = os.getenv("RAILWAY_PUBLIC_DOMAIN", "").strip()

ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".railway.app", "*.railway.app"]


def _host_from_url(raw: str) -> str:
    cleaned = raw.replace("https://", "").replace("http://", "").split("/")[0]
    return cleaned


if RAILWAY_STATIC_URL:
    host = _host_from_url(RAILWAY_STATIC_URL)
    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

if RAILWAY_PUBLIC_DOMAIN:
    host = _host_from_url(RAILWAY_PUBLIC_DOMAIN)
    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# CSRF trusted origins for Railway
# Start with base patterns
CSRF_TRUSTED_ORIGINS: list[str] = [
    "https://*.railway.app",
    "https://*.up.railway.app",
]

if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend(
        ["http://localhost", "http://127.0.0.1", "http://0.0.0.0"]
    )

# Check if Railway set CSRF_TRUSTED_ORIGINS env var (fix missing schemes)
_env_csrf_origins = os.getenv("CSRF_TRUSTED_ORIGINS", "").strip()
if _env_csrf_origins:
    # Clear any Railway-injected value without schemes and rebuild it properly
    for origin in _env_csrf_origins.split(","):
        origin = origin.strip()
        if origin and not origin.startswith(("http://", "https://")):
            # Railway might inject domains without schemes - add https://
            origin = f"https://{origin}"
        if origin and origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)


def _origin_with_scheme(raw: str) -> str:
    """Ensure URL has a scheme prefix (https:// or http://)."""
    cleaned = raw.strip()
    if not cleaned:
        return ""
    # Remove any leading slashes or spaces
    cleaned = cleaned.lstrip('/')
    # Check if scheme is already present
    if cleaned.startswith(("http://", "https://")):
        return cleaned
    # Add https:// scheme
    return f"https://{cleaned}"


if RAILWAY_STATIC_URL:
    origin = _origin_with_scheme(RAILWAY_STATIC_URL)
    if origin and origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

if RAILWAY_PUBLIC_DOMAIN:
    origin = _origin_with_scheme(RAILWAY_PUBLIC_DOMAIN)
    if origin and origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

# Security settings for production
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "storages",
    "accounts",
    "leads",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "leadcrm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "leads.context_processors.stripe_settings",
            ],
        },
    },
]

WSGI_APPLICATION = "leadcrm.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

import dj_database_url

DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

BATCHDATA_API_KEY = os.getenv("BATCHDATA_API_KEY", "")
ATTOM_API_KEY = os.getenv("ATTOM_API_KEY", "")
COURTLISTENER_API_KEY = os.getenv("COURTLISTENER_API_KEY", "")

LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "accounts:profile"
LOGOUT_REDIRECT_URL = "parcel_search"


def _decimal_setting(key: str, default: str) -> Decimal:
    raw = os.getenv(key)
    if raw:
        try:
            return Decimal(raw)
        except (InvalidOperation, ValueError):
            pass
    return Decimal(default)


def _float_setting(key: str, default: float) -> float:
    raw = os.getenv(key)
    if raw:
        try:
            return float(raw)
        except ValueError:
            pass
    return default


def _int_setting(key: str, default: int) -> int:
    raw = os.getenv(key)
    if raw:
        try:
            return int(raw)
        except ValueError:
            pass
    return default


def _bool_setting(key: str, default: bool) -> bool:
    raw = os.getenv(key)
    if raw is None:
        return default
    return raw.strip().lower() not in {"0", "false", "no", "off"}


_skiptrace_base_cost = _decimal_setting("SKIPTRACE_BASE_COST", "0.07")
_skiptrace_dnc_cost_per_phone = _decimal_setting(
    "SKIPTRACE_DNC_COST_PER_PHONE", "0.002"
)
try:
    _skiptrace_phone_lookups = int(os.getenv("SKIPTRACE_MAX_PHONE_LOOKUPS", "3"))
except ValueError:
    _skiptrace_phone_lookups = 3
_skiptrace_markup = _decimal_setting("SKIPTRACE_MARKUP_RATE", "0.30")
STRIPE_PROCESSING_FEE_RATE = _decimal_setting("STRIPE_PROCESSING_FEE_RATE", "0.05")
STRIPE_PROCESSING_FEE_FIXED = _decimal_setting("STRIPE_PROCESSING_FEE_FIXED", "0.30")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
STRIPE_PRICE_INDIVIDUAL_STANDARD = os.getenv("STRIPE_PRICE_INDIVIDUAL_STANDARD", "")
STRIPE_PRICE_TEAM_STANDARD = os.getenv("STRIPE_PRICE_TEAM_STANDARD", "")
STRIPE_PRICE_TEAM_PLUS = os.getenv("STRIPE_PRICE_TEAM_PLUS", "")

SKIPTRACE_MARKUP_RATE = _skiptrace_markup
SKIPTRACE_VENDOR_COST_PER_LOOKUP = (
    _skiptrace_base_cost
    + (_skiptrace_dnc_cost_per_phone * Decimal(_skiptrace_phone_lookups))
).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
SKIPTRACE_MARKUP_AMOUNT_PER_LOOKUP = (
    SKIPTRACE_VENDOR_COST_PER_LOOKUP * SKIPTRACE_MARKUP_RATE
).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)

_raw_skiptrace_cost = os.getenv("SKIPTRACE_COST_PER_LOOKUP")
if _raw_skiptrace_cost:
    try:
        SKIPTRACE_COST_PER_LOOKUP = Decimal(_raw_skiptrace_cost)
    except (InvalidOperation, ValueError):
        SKIPTRACE_COST_PER_LOOKUP = None
else:
    SKIPTRACE_COST_PER_LOOKUP = None

if SKIPTRACE_COST_PER_LOOKUP is None:
    SKIPTRACE_COST_PER_LOOKUP = (
        SKIPTRACE_VENDOR_COST_PER_LOOKUP + SKIPTRACE_MARKUP_AMOUNT_PER_LOOKUP
    ).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
else:
    # When overriding the final price, recompute markup amount to reflect configured rate.
    SKIPTRACE_MARKUP_AMOUNT_PER_LOOKUP = (
        SKIPTRACE_COST_PER_LOOKUP - SKIPTRACE_VENDOR_COST_PER_LOOKUP
    ).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)

if SKIPTRACE_MARKUP_AMOUNT_PER_LOOKUP < Decimal("0"):
    SKIPTRACE_MARKUP_AMOUNT_PER_LOOKUP = Decimal("0.00")


MAILER_CONTACT_PHONE = os.getenv("MAILER_CONTACT_PHONE", "555-5555")
MAILER_TEXT_KEYWORD = os.getenv("MAILER_TEXT_KEYWORD", "HOME")
MAILER_QR_BASE_URL = os.getenv("MAILER_QR_BASE_URL")
MAILER_QR_IMAGE_ENDPOINT = os.getenv(
    "MAILER_QR_IMAGE_ENDPOINT",
    "https://api.qrserver.com/v1/create-qr-code/?size=320x320&data=__DATA__",
)
MAILER_AGENT_NAME = os.getenv("MAILER_AGENT_NAME", "")
MAILER_AGENT_TITLE = os.getenv("MAILER_AGENT_TITLE", "")
MAILER_AGENT_COMPANY = os.getenv("MAILER_AGENT_COMPANY", "")
MAILER_AGENT_TAGLINE = os.getenv("MAILER_AGENT_TAGLINE", "Your Neighborhood Specialist")
MAILER_AGENT_PHOTO_PATH = os.getenv(
    "MAILER_AGENT_PHOTO_PATH", "leadcrm/photos/Home.png"
)

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
MAILER_OPENAI_MODEL = os.getenv("MAILER_OPENAI_MODEL", "gpt-4o-mini")
MAILER_OPENAI_TEMPERATURE = _float_setting("MAILER_OPENAI_TEMPERATURE", 0.65)
MAILER_OPENAI_MAX_TOKENS = _int_setting("MAILER_OPENAI_MAX_TOKENS", 700)
MAILER_OPENAI_TIMEOUT = _float_setting("MAILER_OPENAI_TIMEOUT", 15.0)
MAILER_AI_ENABLED = _bool_setting("MAILER_AI_ENABLED", bool(OPENAI_API_KEY))
MAILER_DEFAULT_PROMPT = os.getenv("MAILER_DEFAULT_PROMPT", "concise_letter")
MAILER_ZILLOW_TIMEOUT = _float_setting("MAILER_ZILLOW_TIMEOUT", 6.0)
MAILER_ZILLOW_USER_AGENT = os.getenv(
    "MAILER_ZILLOW_USER_AGENT",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
)

# ATTOM API cache settings
# Cross-user cache age in days - ATTOM data older than this will be refetched
ATTOM_CACHE_MAX_AGE_DAYS = _int_setting("ATTOM_CACHE_MAX_AGE_DAYS", 60)

# AWS S3 Configuration
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1")
AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN")

# Use S3 for storage if credentials are provided
USE_S3 = bool(AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY and AWS_STORAGE_BUCKET_NAME)

if USE_S3:
    # S3 Configuration
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }
    AWS_QUERYSTRING_AUTH = False

    # Static files location in S3
    AWS_STATIC_LOCATION = "static"
    STORAGES = {
        "default": {
            "BACKEND": "leadcrm.storage_backends.MediaStorage",
        },
        "staticfiles": {
            "BACKEND": "leadcrm.storage_backends.StaticStorage",
        },
    }
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_STATIC_LOCATION}/"

    # Media files location in S3
    AWS_MEDIA_LOCATION = "media"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_MEDIA_LOCATION}/"
else:
    # Local storage fallback
    STATIC_URL = "static/"
    STATIC_ROOT = BASE_DIR / "staticfiles"
    MEDIA_URL = "media/"
    MEDIA_ROOT = BASE_DIR / "media"

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {name} - {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "leads": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
