# Generated by Django 5.2.3 on 2025-10-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_remove_attomdata_lead_remove_lead_saved_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attomdata',
            name='foreclosure_auction_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='foreclosure_default_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='foreclosure_document_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='foreclosure_estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='foreclosure_judgment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='foreclosure_recording_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='foreclosure_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='mortgage_due_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='mortgage_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='mortgage_lender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='mortgage_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='mortgage_loan_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='mortgage_loan_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='mortgage_recording_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='mortgage_term_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='propensity_to_default_decile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='propensity_to_default_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='tax_amount_annual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='tax_assessed_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='tax_assessment_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attomdata',
            name='tax_delinquent_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
