# Generated by Django 5.2.3 on 2025-11-02 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_attomdata_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_id', models.IntegerField(blank=True, null=True)),
                ('loc_id', models.CharField(blank=True, max_length=200)),
                ('action_type', models.CharField(choices=[('foreclosure', 'Foreclosure'), ('eviction', 'Eviction/Summary Process'), ('civil_judgment', 'Civil Judgment'), ('land_court', 'Land Court Case'), ('bankruptcy_ch7', 'Bankruptcy Chapter 7'), ('bankruptcy_ch11', 'Bankruptcy Chapter 11'), ('bankruptcy_ch13', 'Bankruptcy Chapter 13'), ('federal_civil', 'Federal Civil Case'), ('federal_criminal', 'Federal Criminal Case'), ('state_civil', 'State Civil Case'), ('state_criminal', 'State Criminal Case'), ('probate', 'Probate/Estate Matter'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('filed', 'Filed'), ('pending', 'Pending'), ('active', 'Active'), ('dismissed', 'Dismissed'), ('settled', 'Settled'), ('judgment', 'Judgment Entered'), ('closed', 'Closed'), ('appealed', 'Under Appeal')], default='filed', max_length=20)),
                ('court', models.CharField(choices=[('ma_housing', 'MA Housing Court'), ('ma_district', 'MA District Court'), ('ma_superior', 'MA Superior Court'), ('ma_land', 'MA Land Court'), ('ma_probate', 'MA Probate & Family Court'), ('ma_appeals', 'MA Appeals Court'), ('ma_sjc', 'MA Supreme Judicial Court'), ('federal_district_ma', 'US District Court (MA)'), ('federal_bankruptcy_ma', 'US Bankruptcy Court (MA)'), ('federal_1st_circuit', 'US Court of Appeals (1st Circuit)'), ('federal_supreme', 'US Supreme Court'), ('other', 'Other Court')], max_length=50)),
                ('case_number', models.CharField(help_text='Court case/docket number', max_length=100)),
                ('plaintiff', models.CharField(blank=True, help_text='Plaintiff/petitioner name', max_length=255)),
                ('defendant', models.CharField(blank=True, help_text='Defendant/respondent name', max_length=255)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('judgment_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('amount_claimed', models.DecimalField(blank=True, decimal_places=2, help_text='Amount claimed/sought', max_digits=12, null=True)),
                ('judgment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Judgment amount awarded', max_digits=12, null=True)),
                ('source', models.CharField(blank=True, help_text="Where this case was found (e.g., 'PACER', 'MA Trial Court eAccess', 'CourtListener')", max_length=255)),
                ('source_url', models.URLField(blank=True, help_text='Link to case docket/details')),
                ('pacer_case_id', models.CharField(blank=True, help_text='PACER case ID if applicable', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief description of the case')),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of file paths or URLs to court documents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-filing_date', '-created_at'],
                'indexes': [models.Index(fields=['town_id', 'loc_id'], name='leads_legal_town_id_1f4d41_idx'), models.Index(fields=['status'], name='leads_legal_status_f0298b_idx'), models.Index(fields=['action_type'], name='leads_legal_action__019486_idx'), models.Index(fields=['case_number'], name='leads_legal_case_nu_d90ab7_idx'), models.Index(fields=['filing_date'], name='leads_legal_filing__338425_idx')],
            },
        ),
        migrations.CreateModel(
            name='LienRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_id', models.IntegerField()),
                ('loc_id', models.CharField(max_length=200)),
                ('lien_type', models.CharField(choices=[('mortgage', 'Mortgage'), ('tax_municipal', 'Municipal Tax Lien'), ('tax_federal', 'Federal Tax Lien'), ('tax_state', 'State Tax Lien'), ('mechanics', 'Mechanics Lien'), ('irs', 'IRS Lien'), ('ucc', 'UCC Filing (Personal Property)'), ('judgment', 'Judgment Lien'), ('hoa', 'HOA Lien'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('discharged', 'Discharged'), ('satisfied', 'Satisfied'), ('partial', 'Partially Released')], default='active', max_length=20)),
                ('lien_holder', models.CharField(help_text='Name of lien holder/creditor', max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Lien amount in dollars', max_digits=12, null=True)),
                ('recording_date', models.DateField(blank=True, null=True)),
                ('book_number', models.CharField(blank=True, help_text='Registry book number', max_length=50)),
                ('page_number', models.CharField(blank=True, help_text='Registry page number', max_length=50)),
                ('instrument_number', models.CharField(blank=True, help_text='Document/instrument number', max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_book_number', models.CharField(blank=True, max_length=50)),
                ('release_page_number', models.CharField(blank=True, max_length=50)),
                ('release_instrument_number', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, help_text="Where this lien was found (e.g., 'Essex County Registry', 'Town Treasurer PDF')", max_length=255)),
                ('source_url', models.URLField(blank=True, help_text='Link to source document/page')),
                ('notes', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of file paths or URLs to supporting documents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lien_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recording_date', '-created_at'],
                'indexes': [models.Index(fields=['town_id', 'loc_id'], name='leads_lienr_town_id_c21b0f_idx'), models.Index(fields=['status'], name='leads_lienr_status_68a397_idx'), models.Index(fields=['lien_type'], name='leads_lienr_lien_ty_3469b1_idx'), models.Index(fields=['recording_date'], name='leads_lienr_recordi_aa8602_idx')],
            },
        ),
    ]
